services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calendar_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"   # ローカルからもアクセスできるようにする
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: